- src: http://github.com/websoft9/role_common

- src: http://github.com/websoft9/role_cloud
  
- src: http://github.com/websoft9/role_docker

- src: http://github.com/websoft9/role_nginx
  
- src: http://github.com/websoft9/role_init

- src: http://github.com/websoft9/role_preend

- src: http://github.com/websoft9/role_end
