---
- name: Delete superset dir for sec_installation
  shell: rm -rf /data/wwwroot/superset

- name: Create dir for superset
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  loop: 
    - /data/db/postgresql
    - /data/db/redis

- name: Clone superset in Websoft9 
  git:
    repo: "{{superset_git_url}}"
    dest: "/data/wwwroot/superset"
    version: dev

- name: Run the docker-compose
  shell: |
    docker-compose up -d
    sleep 30
  args:
    chdir: /data/wwwroot/superset

- name: Create a Apache Log symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
  - {src: /data/wwwroot/superset/postgresql_data/,dest: /data/db/postgresql/data}
  - {src: /data/wwwroot/superset/redis/,dest: /data/db/redis/data}

# check superset,postgresql,redis version and service state
- name: Check superset,postgresql,redis version
  shell: >
    sudo echo -e "superset_version: `docker exec -it superset_app /bin/bash -c 'cat /app/superset-frontend/package.json |grep version |sed -n 1p |cut -d: -f 2'`\n" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "postgres_version: `docker exec -it superset_db /bin/bash -c 'psql -V |cut -d " " -f 3'`\n" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "redis_version: `docker exec -it superset_cache /bin/bash -c '/usr/local/bin/redis-server -v |cut -d " " -f 3 |cut -d "=" -f 2'`\n" |sudo tee -a /data/logs/install_version.txt
    
- name: Check superset Service
  shell: sudo docker ps | grep superset
  register: check_superset_service
  notify: check_superset_service

    


