#1 Prepare for install
- name: Create Superset User
  user:
    name: superset
    shell: /usr/sbin/nologin
    create_home: no

- name: delete old installfiles
  shell: rm -rf /data/wwwroot/*

- name: Git clone latest source
  shell: |
    git clone https://github.com/apache/superset.git
    cd superset
    docker-compose -f docker-compose-non-dev.yml up
  args:
    chdir: /data/wwwroot

- name: Create Superset-data directory
  file:
    path: /data/wwwroot/superset_data
    state: directory
    owner: superset
    group: superset
    
#2 Install by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#4 configure Superset
- name: Create soft link
  shell:
    ln -sf /var/lib/docker/volumes /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/docker  /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/postgre  /data/wwwroot/superset_data
    ln -sf /data/wwwroot/superset/postgre-frontend  /data/wwwroot/superset_data

#5 version output
- name: Check Superset Version
  shell: |
    sudo echo -e "superset_version: `docker exec -it superset_app /bin/bash -c 'cat /app/superset-frontend/package.json |grep version |sed -n 1p |cut -d: -f 2'`\n" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "postgres_version: `docker exec -it superset_db /bin/bash -c 'psql -V |cut -d " " -f 3'`\n" |sudo tee -a /data/logs/install_version.txt
    sudo echo -e "redis_version: `docker exec -it superset_cache /bin/bash -c '/usr/local/bin/redis-server -v |cut -d " " -f 3 |cut -d "=" -f 2'`\n" |sudo tee -a /data/logs/install_version.txt

